### ISSUE TITLE
Github에서의 Auto Branch Delete기능에 따른 Mergify Rule 변경

### ISSUE THREAD

**Issue by SeonHyungJo** [Im-D/Dev-Docs#81]
요즘 Github에서 sponsor, template 등등 새로운 기능 마구마구 만들어 내고 있는데, 이번에? 새로 추가된 기능으로 Merge된 브랜치를 자동으로 지우는 기능이 생겼습니다.

![image](https://user-images.githubusercontent.com/24274424/64397604-d182da00-d09c-11e9-8c71-5899c1aacd74.png)

이는 기존에 우리가 사용하고 있는 Mergify Rule과 동일한 기능입니다.

결론적으로

- mergify.xml rule 제거
- Dev-Docs  Auto branch delete 기능활성화

수정을 원합니다. 

어떠신지 의견주세요

**Comment by devjinius** [comment]
현재와 동일한 기능인데 깃헙의 기능으로 추가된 듯 하네요. 좋습니다.

**Comment by BKJang** [comment]
기존 Mergify 기능에서 머지된 브랜치를 자동 삭제하는 기능만 Github의 기능을 사용하자는거죠? 좋습니다 👍

**Comment by JHRla** [comment]
넵 좋습니다! 👍

**Comment by SeonHyungJo** [comment]
> 넵 좋습니다! 👍

#82  해당 PR에서 승인처리해주시면 감사하겠습니다.
